### ISSUE TITLE
Text of QuickRepliesMessage is not displayed

### ISSUE THREAD

**Issue by tagazok** [Botfuel/botfuel-webchat-client#21]
As per the [documentation](https://docs.botfuel.io/dialog/reference/messages#quickrepliesmessage), to create a QuickRepliesMessage : 
```javascript
new QuickrepliesMessage(['1', '2', '3', '4', '5'], { text: 'Please give me a note.' });
```

However, the text "Please give me a note" is not displayed by the Webchat client:

![screen shot 2018-06-04 at 15 02 23](https://user-images.githubusercontent.com/2637742/40919034-8dc7ab54-6808-11e8-899c-80774e0af1c0.png)

**Comment by KevinDepuydt** [comment]
fixed with version **3.17.1**
